services:
  app_database:
    image: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: app_user
      POSTGRES_DB: app_db
      POSTGRES_PASSWORD: app_password
    ports:
      - "5432:5432"

  todofast:
    entrypoint: ./entrypoint.sh
    build: .
    container_name: todofast
    depends_on:
      - app_database
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql+psycopg://app_user:app_password@app_database:5432/app_db

volumes:
  pgdata:
